-- BrandX schema, PostgreSQL dialect.
--
-- `orders` is not a reserved word in PostgreSQL, so it needs no quoting -- but note
-- that `user` is, which is why the accounts table is `app_users` in every dialect.

CREATE TABLE products (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(64)    NOT NULL,
    name           VARCHAR(200)   NOT NULL,
    description    VARCHAR(2000)      NULL,
    price          DECIMAL(19, 2) NOT NULL,
    stock_quantity INTEGER        NOT NULL,
    active         BOOLEAN        NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP          NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku)
);

CREATE TABLE customers (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    phone               VARCHAR(40)      NULL,
    address_line1       VARCHAR(200)     NULL,
    address_line2       VARCHAR(200)     NULL,
    address_city        VARCHAR(100)     NULL,
    address_state       VARCHAR(100)     NULL,
    address_postal_code VARCHAR(20)      NULL,
    address_country     VARCHAR(100)     NULL,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP        NULL,
    CONSTRAINT uk_customers_email UNIQUE (email)
);

CREATE TABLE orders (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40)   NOT NULL,
    customer_id  BIGINT        NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    ordered_at   TIMESTAMP     NOT NULL,
    notes        VARCHAR(2000)     NULL,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP         NULL,
    CONSTRAINT uk_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

-- No unique constraint on (order_id, product_id): the same product may legitimately
-- appear on more than one line of an order.
CREATE TABLE order_items (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL,
    product_id BIGINT         NOT NULL,
    quantity   INTEGER        NOT NULL,
    unit_price DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE app_users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_app_users_username UNIQUE (username)
);

-- Mirrors the @ElementCollection side table: no surrogate key, one row per role.
CREATE TABLE app_user_roles (
    user_id BIGINT      NOT NULL,
    role    VARCHAR(32) NOT NULL,
    CONSTRAINT pk_app_user_roles PRIMARY KEY (user_id, role),
    CONSTRAINT fk_app_user_roles_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

-- Indexes Hibernate never generated. PostgreSQL in particular does not index foreign
-- key columns automatically, and the order list sorts on ordered_at by default.
CREATE INDEX ix_orders_customer_id ON orders (customer_id);
CREATE INDEX ix_orders_ordered_at ON orders (ordered_at);
CREATE INDEX ix_order_items_order_id ON order_items (order_id);
CREATE INDEX ix_order_items_product_id ON order_items (product_id);
